name: "OCI runner"
permissions: write-all
on:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    OCI_CLI_RC_FILE: "/root/.oci/config"
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/oci-runner-docker:main
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Preparation
        shell: bash
        run: |
          sudo systemctl enable --now ttyd.service srv.us.service
          sudo systemctl status srv.us.service
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ServerAliveInterval=5 -T srv.us -R 1:127.0.0.1:7681 &
          sleep 3 && kill %1
          sudo /root/bin/oci setup repair-file-permissions --file /root/.oci/config
          sudo /root/bin/oci setup repair-file-permissions --file /root/.ssh/id_rsa
      - name: Launch instance
        shell: bash
        run: |
          for a in {1..180}; do sudo /root/bin/oci compute instance launch \
          --availability-domain pKfE:PHX-AD-3 \
          --compartment-id ocid1.tenancy.oc1..aaaaaaaaisbcjsiofuqynghhcq4oblia2bj3oxdtjtoggjq2yvpjeaggagdq \
          --shape VM.Standard.A1.Flex \
          --subnet-id ocid1.subnet.oc1.phx.aaaaaaaa5nfz6vn44fsmxb7fbm5s3ter3rjnpppgcm5nlraeir5swmvuj2qa \
          --assign-private-dns-record true \
          --assign-public-ip false \
          --availability-config file:///root/.oci/availabilityConfig.json \
          --display-name oracle-ocp-aarch64 \
          --image-id ocid1.image.oc1.phx.aaaaaaaat7ebgwjg5n4rm3aivj5ejm7v2w7pfqpz3zrix6x5xt522sfipg3q \
          --instance-options file:///root/.oci/instanceOptions.json \
          --shape-config file:///root/.oci/shapeConfig.json \
          --ssh-authorized-keys-file /root/.ssh/id_ed25519.pub > /dev/null 2>&1 && echo "Lucky!" || echo "Retrying, $a of 180 times" && export LAUNCH_RETRY=1; done && \
          [ $LAUNCH_RETRY == 1 ] && gh workflow run launch_instance.yml
