name: OCI runner #1
on:
  push:
    branches:
      - 'main'
  # schedule:
  #   - cron: '*/10 * * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["OCI runner #2"]
    types: [completed]
jobs:
  on-failure:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/oci-runner-docker:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Run
        shell: bash
        run: |
          export OCI_CLI_RC_FILE=/root/.oci/config
          sudo /root/bin/oci setup repair-file-permissions --file /root/.oci/config
          sudo /root/bin/oci setup repair-file-permissions --file /root/.ssh/id_rsa
          for a in $(seq 1 120); do sudo /root/bin/oci compute instance launch \
          --availability-domain pKfE:PHX-AD-3 \
          --compartment-id ocid1.tenancy.oc1..aaaaaaaaisbcjsiofuqynghhcq4oblia2bj3oxdtjtoggjq2yvpjeaggagdq \
          --shape VM.Standard.A1.Flex \
          --subnet-id ocid1.subnet.oc1.phx.aaaaaaaa5nfz6vn44fsmxb7fbm5s3ter3rjnpppgcm5nlraeir5swmvuj2qa \
          --assign-private-dns-record true \
          --assign-public-ip false \
          --availability-config file:///root/.oci/availabilityConfig.json \
          --display-name oracle-ocp-aarch64 \
          --image-id ocid1.image.oc1.phx.aaaaaaaat7ebgwjg5n4rm3aivj5ejm7v2w7pfqpz3zrix6x5xt522sfipg3q \
          --instance-options file:///root/.oci/instanceOptions.json \
          --shape-config file:///root/.oci/shapeConfig.json \
          --ssh-authorized-keys-file /root/.ssh/id_ed25519.pub; sleep 60; done
