# This is a basic workflow to help you get started with Actions

name: OCI runner

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/ubuntu-docker:oci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Preparation
        run: sudo mkdir -p /root/.oci /root/.ssh
      - name: Install step 1
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/availabilityConfig.son"
      - name: Install step 2
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/config"
      - name: Install step 3
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_ed25519.pub"
      - name: Install step 4
        working-directory: /root/.oci
        run: sudo rm id_rsa; curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_rsa"
      - name: Install step 5
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instance_launch.sh"
      - name: Install step 6
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instanceOptions.json"
      - name: Install step 7
        working-directory: /root/.oci
        run: sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/shapeConfig.json"
      - name: Run
        run: sudo /bin/bash /root/.oci/instance_launch.sh
      - name: Check output
        run: for a in 1 2 3; do sudo cat /root/.oci/instance_launch.$a.log; done

