name: OCI runner
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '*/7 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/ubuntu-docker:oci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Preparation
        run: sudo mkdir -p /root/.oci /root/.ssh
      - name: Install step 1
        working-directory: /root/.oci
        run: |
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/availabilityConfig.json"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/config"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instance_launch.sh"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instanceOptions.json"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/shapeConfig.json"
      - name: Install step 2
        working-directory: /root/.ssh
        run: |
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_ed25519.pub" && \
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_rsa"
      - name: Run
        shell: bash
        run: |
          export OCI_CLI_RC_FILE=/root/.oci/config
          sudo /root/bin/oci setup repair-file-permissions --file /root/.oci/config
          sudo /root/bin/oci setup repair-file-permissions --file /root/.ssh/id_rsa
          for a in 1 2 3; do sudo /root/bin/oci compute instance launch \
          --availability-domain pKfE:PHX-AD-$a \
          --compartment-id ocid1.tenancy.oc1..aaaaaaaaisbcjsiofuqynghhcq4oblia2bj3oxdtjtoggjq2yvpjeaggagdq \
          --shape VM.Standard.A1.Flex \
          --subnet-id ocid1.subnet.oc1.phx.aaaaaaaa5nfz6vn44fsmxb7fbm5s3ter3rjnpppgcm5nlraeir5swmvuj2qa \
          --assign-private-dns-record true \
          --assign-public-ip false \
          --availability-config file:///root/.oci/availabilityConfig.json \
          --display-name oracle-ocp-aarch64 \
          --image-id ocid1.image.oc1.phx.aaaaaaaat7ebgwjg5n4rm3aivj5ejm7v2w7pfqpz3zrix6x5xt522sfipg3q \
          --instance-options file:///root/.oci/instanceOptions.json \
          --shape-config file:///root/.oci/shapeConfig.json \
          --ssh-authorized-keys-file /root/.ssh/id_ed25519.pub & done
          while [[ "$(jobs | wc -l)" -ne "1" ]]; do sleep 5; done
