# This is a basic workflow to help you get started with Actions

name: OCI runner

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/ubuntu-docker:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install
        run: (wget -O /tmp/oci-runner.install.sh "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/d3aa3a1834cf3d105a5bdf5f622417103599bdbe/oci-runner.install.sh" && /bin/bash /tmp/oci-runner.install.sh)
      - name: Run
        run: /bin/bash /root/.oci/instance_launch.sh
      - name: Check output
        run: for a in 1 2 3; do cat /root/.oci/instance_launch.$a.log; done

