# This is a basic workflow to help you get started with Actions

name: OCI runner

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/ubuntu-docker:oci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install
        run: sudo mkdir -p /root/.oci /root/.ssh; for a in availabilityConfig.son config id_ed25519.pub id_rsa instance_launch.sh instanceOptions.json shapeConfig.json; do sudo /bin/bash -c 'cd /root/.oci && curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/'$a'"'; done && for a in id_ed25519.pub id_rsa; do sudo mv -f /root/.oci/$a /root/.ssh/ && sudo chmod 600 /root/.oci/$a; done
      - name: Run
        run: sudo /bin/bash /root/.oci/instance_launch.sh
      - name: Check output
        run: for a in 1 2 3; do sudo cat /root/.oci/instance_launch.$a.log; done

