name: OCI runner
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/ubuntu-docker:oci-runner
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Preparation
        run: sudo mkdir -p /root/.oci /root/.ssh
      - name: Install step 1
        working-directory: /root/.oci
        run: |
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/availabilityConfig.son"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/config"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instance_launch.sh"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/instanceOptions.json"
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/shapeConfig.json"
      - name: Install step 2
        working-directory: /root/.ssh
        run: |
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_ed25519.pub" && \
          sudo curl -sLO "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/35deaccdb062f55453ab005ebcdeb3b01607cda1/id_rsa"
      - name: Run
        run: |
          echo Content of /root/.oci/instance_launch.sh:
          cat /root/.oci/instance_launch.sh
          echo Location of oci executable:
          whereis oci
          echo List of file with name oci:
          sudo find / -name oci
          sudo bash /root/.oci/instance_launch.sh
      - name: Check output
        run: for a in 1 2 3; do sudo cat /root/.oci/instance_launch.$a.log; done
