name: Run OCI instance launch API calls

on:
  workflow_dispatch

jobs:
  oci-runner:
    runs-on:
  	container:
  	  image: ghcr.io/musahi0128/ubuntu-docker:main
    steps:
      - name: Install
        run: (wget -O /tmp/oci-runner.install.sh "https://gist.github.com/musahi0128/3831be50e218a4de5018939da52cfe23/raw/d3aa3a1834cf3d105a5bdf5f622417103599bdbe/oci-runner.install.sh" && /bin/bash /tmp/oci-runner.install.sh)
      - name: Run
        run: /bin/bash /root/.oci/instance_launch.sh
      - name: Check output
        run: for a in 1 2 3; do cat /root/.oci/instance_launch.$a.log
