name: "OCI runner test"
on:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/oci-runner-docker:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE; \
          curl -sLO https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb && \
          apt update && dpkg -i gh* || apt install -fyq && \
          apt install -yq tmate && \
          gh workflow run launch_instance.yml || echo "Will be handled in the interactive session" && \
          tmate -F
