name: "OCI runner test"
on:
  workflow_dispatch:
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  launch_instance:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/musahi0128/oci-runner-docker:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Run
        shell: bash
        run: |
          curl -sLO https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb && \
          dpkg -i gh*; \
          apt update && apt install -fyq tmate && \
          gh workflow run launch_instance.yml; \
          tmate -F
